class Solution(object):
    def intToRoman(self, num):
        result=""
        while num>=1000:
            num-=1000
            result+="M"
        if num>=900:
            num-=900
            result+="C"
            result+="M"
        if num>=500:
            num-=500
            result+="D"
        if num>=400:
            num-=400
            result+="C"
            result+="D"
        while num>=100:
            num-=100
            result+="C"
        if num>=90:
            num-=90
            result+="X"
            result+="C"
        if num>=50:
            num-=50
            result+="L"
        if num>=40:
            num-=40
            result+="X"
            result+="L"
        while num>=10:
            num-=10
            result+="X"
        if num>=9:
            num-=9
            result+="I"
            result+="X"
        if num>=5:
            num-=5
            result+="V"